import {
  BookOpenIcon,
  CalendarIcon,
  FilmIcon,
  GithubIcon,
  HomeIcon,
  LinkedinIcon,
  MailIcon,
  MapPinIcon,
  MedalIcon,
  MusicIcon,
  PhoneIcon,
  PlaneIcon,
} from "lucide-react";

export const DATA = {
  header: {
    title: "Hi, I'm Tuan",
    subtitle:
      "A passionate developer who enjoys learning, experimenting, and turning new technologies into practical products",
    avatarUrl: "/avatar.jpg",
  },
  about: {
    title: "About",
    data: [
      "Frontend Developer with 3+ years of experience building and maintaining scalable web applications using React.js and Next.js. Experienced in turning Figma designs into clean, responsive interfaces, while building reusable components and keeping the codebase easy to maintain. Comfortable working with SSR, ISR, and state management to improve performance and user experience. Also able to support backend work when needed, with a strong focus on product quality, stability, and long-term growth.",
      "Good teamwork and communication. Fast learner with a strong adaptation mindset. Interested in performance optimization, source structure, and user experience. Able to work across frontend and backend when the project requires it.",
    ],
  },
  work: {
    title: "Work Experience",
    data: [
      {
        logoUrl: "/fptis.jpg",
        altText: "FPT IS",
        company: "FPT IS",
        title: "Software Engineer",
        start: "Feb 2026",
        end: "Present",
        techStack: [
          "Microservices",
          "Monorepo",
          "React.js",
          "Java Spring Boot",
          "PostgreSQL",
        ],
        description: [
          "Social Protection System — large-scale government system for social protection management with multiple business modules and centralized data handling.",
          "Developed and maintained core modules including category, social facility, staff, beneficiary, and user management.",
          "Built data-heavy administrative screens featuring complex lists, forms, multi-filters, and pagination.",
          "Engineered reusable UI components for tables and inputs to ensure interface consistency and system scalability.",
          "Collaborated on business logic implementation and API synchronization within a microservices and monorepo architecture.",
          "Ensured system stability by handling data flow and performance issues across the full stack.",
        ],
      },
      {
        logoUrl: "/arobid.png",
        altText: "arobid",
        company: "AROBID",
        title: "Frontend Developer",
        start: "Feb 2025",
        end: "Feb 2026",
        techStack: [
          "Monorepo",
          "React.js",
          "Next.js",
          "Payload",
          "Zustand",
          "TanStack Query",
          "Tailwind CSS",
          "MongoDB",
          "Radix UI",
          "Shadcn UI",
        ],
        description: [
          "TradeXpo — Digital Exhibition Platform: built core pages (home, event list, event detail, inner pages) and the full user journey from landing to event and booth interactions.",
          "Integrated a 3D/VR system using Shapespark through iframe and postMessage; developed gamification (check-in, booth interaction, product viewing, rewards).",
          "Integrated CleverTap for user behavior tracking; optimized UX for media-heavy and dynamic pages; aligned implementation with Figma and product flow.",
          "TradeXpo contributed to the platform winning “Excellent Digital Technology Solution” at Vietnam Digital Awards 2025.",
          "CMS Platform — News, FAQ, Career: built a shared CMS for multiple content types; management pages for articles, categories, and structured content.",
          "Applied SSR and ISR for SEO, page speed, and search visibility; supported stable data flow across frontend and backend.",
        ],
      },
      {
        logoUrl: "/dcorp.png",
        altText: "dcorp",
        company: "DCORP R-KEEPER",
        title: "Frontend Developer",
        start: "Mar 2024",
        end: "Feb 2025",
        techStack: [
          "React.js",
          "Next.js",
          "Zustand",
          "TanStack Query",
          "Tailwind CSS",
          "Shadcn UI",
          "Daisy UI",
          "Ant Design",
          "Radix UI",
          "Storybook",
          "Monorepo",
        ],
        description: [
          "Omnichannel Order & Inventory — Highlands Coffee: order flows integrating Shopee, Grab, in-store POS, and internal systems; operational dashboards, goods receipt/issue, and inventory tracking.",
          "Handled large datasets and complex multi-state order workflows; contributed to business configuration screens for real-time retail operations.",
          "Digital e-Menu: Menu, Item Details, Shopping Cart, Order History; temporary bill for real-time spending estimates; cart logic optimized for frequent updates.",
          "Internal Management Platform: data-heavy tables, multi-filters, search, pagination; reporting for call activities, work logs, and tax workflows; integrations (Omicall, ClickUp, GDT).",
          "Internal UI System: reusable components across projects, standardized usage, Storybook documentation, layout fixes and manual UI testing.",
        ],
      },
      {
        logoUrl: "/wisdom.jpg",
        altText: "wisdomrobotics",
        company: "WISDOM ROBOTICS",
        title: "Software Engineer",
        start: "Mar 2023",
        end: "Sep 2023",
        techStack: [
          "Spring Boot",
          "React.js",
          "Spring Data JPA",
          "PostgreSQL",
          "Tailwind CSS",
          "Redux",
        ],
        description: [
          "Vehicle Maintenance System — joined from an early stage; worked with BA on requirements and maintenance workflows.",
          "Developed backend services with Java Spring Boot and PostgreSQL; built frontend screens with Next.js.",
          "Supported modules for vehicles, maintenance schedules, spare parts, and operational data.",
        ],
      },
    ],
  },
  education: {
    title: "Education",
    data: [
      {
        logoUrl: "/stu.png",
        altText: "Saigon Technology University",
        href: "https://stu.edu.vn",
        school: "Saigon Technology University",
        degree: "Bachelor of Engineering in Information Technology",
        start: "2020",
        end: "2024",
      },
    ],
  },
  skills: {
    title: "Skills",
    data: [
      "JavaScript",
      "TypeScript",
      "React.js",
      "Next.js",
      "Zustand",
      "Redux",
      "TanStack Query",
      "Spring Boot",
      "Node.js",
      "Express.js",
      "PostgreSQL",
      "MongoDB",
      "Git",
      "Figma",
      "Docker",
      "SSR",
      "ISR",
      "Monorepo",
      "Microservices",
    ],
  },
  navbar: [
    {
      href: "/#",
      label: "Home",
      icon: HomeIcon,
    },
    {
      href: "https://www.linkedin.com/in/tuan-huynh-916b792b7",
      label: "LinkedIn",
      icon: LinkedinIcon,
    },
    {
      href: "https://github.com/qtuan02",
      label: "GitHub",
      icon: GithubIcon,
    },
  ],
  contact: {
    title: "Contact",
    data: [
      {
        icon: CalendarIcon,
        href: "#",
        label: "20/07/2002",
      },
      {
        icon: PhoneIcon,
        href: "tel:+84393653862",
        label: "(+84) 393 653 862",
      },
      {
        icon: MapPinIcon,
        href: "#",
        label: "District 7, Ho Chi Minh City, Vietnam",
      },
      {
        icon: GithubIcon,
        href: "https://github.com/qtuan02",
        label: "github.com/qtuan02",
      },
      {
        icon: MailIcon,
        href: "mailto:huynhquoctuan200702@gmail.com",
        label: "huynhquoctuan200702@gmail.com",
      },
    ],
  },
  hobbies: {
    title: "Hobbies",
    data: [
      {
        icon: MedalIcon,
        label: "Sport",
      },
      {
        icon: BookOpenIcon,
        label: "Read book",
      },
      {
        icon: PlaneIcon,
        label: "Travel",
      },
      {
        icon: MusicIcon,
        label: "Listen music",
      },
      {
        icon: FilmIcon,
        label: "Watch movie",
      },
    ],
  },
};
