packages:
  - apps/*
  - packages/*
  - toolings/*

catalog:
  "@hookform/resolvers": 4.1.3
  "@tailwindcss/postcss": ^4.1.14
  "@types/node": ^22.0.0
  class-variance-authority: 0.7.1
  dotenv-cli: 8.0.0
  embla-carousel-react: ^8.6.0
  eslint: ^9.38.0
  flag-icons: ^7.5.0
  lucide-react: 0.536.0
  motion: ^12.23.12
  postcss: ^8.5.6
  prettier: ^3.5.3
  react-error-boundary: ^6.0.0
  react-hook-form: 7.62.0
  sonner: 2.0.7
  tailwind-merge: 3.3.1
  tailwind-scrollbar: ^4.0.2
  tailwindcss: 4.1.14
  tw-animate-css: 1.4.0
  typescript: ^5.8.2
  zod: 3.25.76

catalogs:
  next15:
    "@next/third-parties": 15.5.2
    "@t3-oss/env-nextjs": 0.13.8
    jiti: 2.6.1
    next: 15.4.2
    next-intl: 4.3.4
    "@sentry/nextjs": ^10.25.0
    "@sentry/profiling-node": ^10.25.0
  react19:
    "@types/react": 19.1.1
    "@types/react-dom": 19.1.2
    react: ^19.1.0
    react-dom: ^19.1.0
  tanstackquery:
    "@tanstack/react-query": ^5.90.2
    "@tanstack/react-query-devtools": ^5.90.2
