packages:
  - "apps/*"
  - "packages/*"
  - "toolings/*"
catalog:
  "@types/node": ^22.0.0
  eslint: ^9.38.0
  prettier: ^3.5.3
  typescript: ^5.8.2
  dotenv-cli: 8.0.0
  zod: ^3.24.2
  tailwindcss: ^4.1.14
  postcss: ^8.5.6
  "@tailwindcss/postcss": ^4.1.14
  tailwind-merge: ^3.0.2
  tailwind-scrollbar: ^4.0.2
  class-variance-authority: ^0.7.1
  react-error-boundary: ^6.0.0
  react-hook-form: ^7.55.0
  "@hookform/resolvers": ^4.1.3
  lucide-react: ^0.536.0
  flag-icons: ^7.5.0
  embla-carousel-react: ^8.6.0
  tw-animate-css: ^1.3.6
  motion: ^12.23.12
  sonner: ^2.0.7
catalogs:
  tanstackquery:
    "@tanstack/react-query": ^5.90.2
    "@tanstack/react-query-devtools": ^5.90.2
  next15:
    next: 15.4.2
    next-intl: 4.3.4
    "@t3-oss/env-nextjs": 0.13.8
    "@next/third-parties": 15.5.2
    jiti: 2.6.1
  react19:
    react: ^19.1.0
    react-dom: ^19.1.0
    "@types/react": 19.1.1
    "@types/react-dom": 19.1.2
