import { spawnSync } from "node:child_process";
import { rmSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Builds the Publish shell `packages/ui-public` (ADR-0004).
 *
 * rslib emits the JavaScript and the declarations; this script owns the two
 * things around it — emptying the shell's `dist/` first, so a primitive deleted
 * from `src/` cannot survive in a tarball, and generating the one CSS entry
 * afterwards. It is the shell's `build`, not a step anyone runs by hand.
 */

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shellDist = resolve(packageRoot, "../ui-public/dist");

/**
 * The one `@import` a consumer owns rather than this package: `tailwindcss` is
 * a peer dependency, so the entry below is a *fragment* meant to be imported
 * after the consumer's own `@import "tailwindcss"`. Shipping a second copy of
 * that import would emit preflight and every utility layer twice.
 */
const CONSUMER_OWNED_IMPORT = '@import "tailwindcss";\n';

/** The `@import` in `globals.css` that resolves inside the workspace. */
const THEME_IMPORT = '@import "./theme.css";';

/**
 * Two `@custom-variant`s the shadcn registry styles against but Base UI never
 * sets. Losing them compiles every `data-horizontal:`/`data-vertical:` utility
 * in this package down to nothing — no CSS, no error, just a flat slider — so
 * the generated entry is checked for them here as well as in `publish:smoke`.
 */
const LOAD_BEARING_VARIANTS = [
  '@custom-variant data-horizontal (&[data-orientation="horizontal"]);',
  '@custom-variant data-vertical (&[data-orientation="vertical"]);',
] as const;

const GENERATED_HEADER = [
  "/* Generated by packages/ui/scripts/build.ts from @monorepo/tailwind-config —",
  '   do not edit. `theme.css` is inlined; `@import "tailwindcss"` is not, because',
  "   tailwindcss is a peer dependency and your own entry already imports it. */",
  "",
].join("\n");

/**
 * `bun`, `rslib` and friends are `.cmd` shims on Windows, which `spawnSync`
 * only finds through a shell.
 */
const useShell = process.platform === "win32";

function run(command: string, args: string[]): void {
  console.log(`  $ ${[command, ...args].join(" ")}`);
  const result = spawnSync(command, args, {
    cwd: packageRoot,
    stdio: "inherit",
    shell: useShell,
  });

  if (result.status !== 0) {
    throw new Error(`\`${command}\` exited with ${result.status ?? "signal"}`);
  }
}

/** Resolves a `@monorepo/tailwind-config` subpath to a file on disk. */
function resolveTailwindConfig(subpath: string): string {
  return fileURLToPath(
    import.meta.resolve(`@monorepo/tailwind-config/${subpath}`),
  );
}

/**
 * Writes `dist/globals.css` by inlining the workspace's theme into the
 * workspace's globals, so a token edited in `tooling/tailwind` reaches the
 * published package without anyone copying it (spec story 31).
 */
async function buildGlobalsCss(): Promise<void> {
  const [globals, theme] = await Promise.all([
    readFile(resolveTailwindConfig("globals"), "utf8"),
    readFile(resolveTailwindConfig("theme"), "utf8"),
  ]);

  if (!globals.includes(CONSUMER_OWNED_IMPORT)) {
    throw new Error(
      `@monorepo/tailwind-config/globals no longer opens with \`${CONSUMER_OWNED_IMPORT.trim()}\``,
    );
  }
  if (!globals.includes(THEME_IMPORT)) {
    throw new Error(
      `@monorepo/tailwind-config/globals no longer carries \`${THEME_IMPORT}\``,
    );
  }

  const generated =
    GENERATED_HEADER +
    globals
      .replace(CONSUMER_OWNED_IMPORT, "")
      .replace(THEME_IMPORT, theme.trimEnd());

  for (const variant of LOAD_BEARING_VARIANTS) {
    if (!generated.includes(variant)) {
      throw new Error(`generated globals.css lost \`${variant}\``);
    }
  }

  const target = resolve(shellDist, "globals.css");
  await writeFile(target, generated);
  console.log(`  wrote ${target}`);
}

console.log("> Empty the shell's dist/");
rmSync(shellDist, { recursive: true, force: true });

console.log("> Compile src/ and the vendored hook with rslib");
run("rslib", ["build"]);

console.log("> Generate the CSS entry from @monorepo/tailwind-config");
await buildGlobalsCss();
