import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync, rmSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Builds the Publish shell `packages/ui-public` (ADR-0004).
 *
 * rslib emits the JavaScript and the declarations; this script owns the two
 * things around it — emptying the shell's `dist/` first, so a primitive deleted
 * from `src/` cannot survive in a tarball, and generating the one CSS entry
 * afterwards. It is the shell's `build`, not a step anyone runs by hand.
 */

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const shellDist = resolve(packageRoot, "../ui-public/dist");

/**
 * The one `@import` a consumer owns rather than this package: `tailwindcss` is
 * a peer dependency, so the entry below is a *fragment* meant to be imported
 * after the consumer's own `@import "tailwindcss"`. Shipping a second copy of
 * that import would emit preflight and every utility layer twice.
 */
const CONSUMER_OWNED_IMPORT = '@import "tailwindcss";\n';

/** The `@import` in `globals.css` that resolves inside the workspace. */
const THEME_IMPORT = '@import "./theme.css";';

/**
 * Two `@custom-variant`s the shadcn registry styles against but Base UI never
 * sets. Losing them compiles every `data-horizontal:`/`data-vertical:` utility
 * in this package down to nothing — no CSS, no error, just a flat slider — so
 * the generated entry is checked for them here as well as in `publish:smoke`.
 */
const LOAD_BEARING_VARIANTS = [
  '@custom-variant data-horizontal (&[data-orientation="horizontal"]);',
  '@custom-variant data-vertical (&[data-orientation="vertical"]);',
] as const;

const GENERATED_HEADER = [
  "/* Generated by the workspace's Tailwind config — do not edit. `theme.css` is",
  '   inlined; `@import "tailwindcss"` is not, because tailwindcss is a peer',
  "   dependency and your own entry already imports it. */",
  "",
].join("\n");

/**
 * The workspace's own scope. Nothing published may name it — not as an import,
 * which no consumer can resolve, and not in prose either, which would point a
 * reader at a package that does not exist on npm. `publish:smoke` asserts the
 * same thing on the tarball; failing here says *which* source line caused it.
 */
const WORKSPACE_SCOPE = "@monorepo/";

/**
 * `bun`, `rslib` and friends are `.cmd` shims on Windows, which `spawnSync`
 * only finds through a shell. Unlike `scripts/publish-smoke.ts` this needs no
 * per-argument quoting: every argument below is a literal with no spaces, and
 * the one path that could hold one — the working directory — is passed as an
 * option rather than on the command line.
 */
const useShell = process.platform === "win32";

function run(command: string, args: string[]): void {
  console.log(`  $ ${[command, ...args].join(" ")}`);
  const result = spawnSync(command, args, {
    cwd: packageRoot,
    stdio: "inherit",
    shell: useShell,
  });

  if (result.status !== 0) {
    throw new Error(`\`${command}\` exited with ${result.status ?? "signal"}`);
  }
}

/** Resolves a `@monorepo/tailwind-config` subpath to a file on disk. */
function resolveTailwindConfig(subpath: string): string {
  return fileURLToPath(
    import.meta.resolve(`@monorepo/tailwind-config/${subpath}`),
  );
}

/**
 * Writes `dist/globals.css` by inlining the workspace's theme into the
 * workspace's globals, so a token edited in `tooling/tailwind` reaches the
 * published package without anyone copying it (spec story 31).
 */
async function buildGlobalsCss(): Promise<void> {
  const [globals, theme] = await Promise.all([
    readFile(resolveTailwindConfig("globals"), "utf8"),
    readFile(resolveTailwindConfig("theme"), "utf8"),
  ]);

  if (!globals.includes(CONSUMER_OWNED_IMPORT)) {
    throw new Error(
      `@monorepo/tailwind-config/globals no longer opens with \`${CONSUMER_OWNED_IMPORT.trim()}\``,
    );
  }
  if (!globals.includes(THEME_IMPORT)) {
    throw new Error(
      `@monorepo/tailwind-config/globals no longer carries \`${THEME_IMPORT}\``,
    );
  }

  const generated =
    GENERATED_HEADER +
    globals
      .replace(CONSUMER_OWNED_IMPORT, "")
      .replace(THEME_IMPORT, theme.trimEnd());

  for (const variant of LOAD_BEARING_VARIANTS) {
    if (!generated.includes(variant)) {
      throw new Error(`generated globals.css lost \`${variant}\``);
    }
  }

  if (generated.includes(WORKSPACE_SCOPE)) {
    throw new Error(
      `generated globals.css names \`${WORKSPACE_SCOPE}\` — reword the comment ` +
        "in tooling/tailwind, which is published verbatim inside this file",
    );
  }

  const target = resolve(shellDist, "globals.css");
  await writeFile(target, generated);
  console.log(`  wrote ${target}`);
}

/** Every `from "…"` / `import "…"` specifier that starts with a dot. */
const RELATIVE_SPECIFIER = /(?:from|import)\s*"(\.[^"]*)"/g;

/**
 * Fails the build when an emitted module points at a file that is not there.
 *
 * This is the one guard the shape of `rslib.config.ts` needs and cannot state
 * itself. The vendored hook is reached through a hard-coded `../internal/`
 * prefix in `output.externals`, which is correct only while every output file
 * sits exactly one level under `dist/` — a new `src/x.tsx`, or a third folder
 * beside `components/` and `utils/`, silently breaks it. Nothing else notices:
 * the specifier assertions in `publish:smoke` check what a path *says*, not
 * whether it resolves, and a consumer only finds out when their bundler tries
 * to follow it.
 */
function assertRelativeImportsResolve(): void {
  const broken: string[] = [];

  function walk(directory: string): void {
    for (const entry of readdirSync(directory, { withFileTypes: true })) {
      const path = join(directory, entry.name);
      if (entry.isDirectory()) {
        walk(path);
        continue;
      }
      if (!path.endsWith(".js") && !path.endsWith(".d.ts")) {
        continue;
      }

      const text = readFileSync(path, "utf8");
      for (const match of text.matchAll(RELATIVE_SPECIFIER)) {
        const specifier = match[1];
        if (specifier === undefined) {
          continue;
        }

        // A declaration file imports its neighbour by the `.js` name ESM will
        // use at runtime; on disk that neighbour is the `.d.ts` beside it.
        const target = path.endsWith(".d.ts")
          ? specifier.replace(/\.js$/, ".d.ts")
          : specifier;

        if (!existsSync(resolve(dirname(path), target))) {
          broken.push(`${path} → ${specifier}`);
        }
      }
    }
  }

  walk(shellDist);

  if (broken.length > 0) {
    throw new Error(
      [
        `${broken.length} import(s) in dist/ resolve to nothing:`,
        ...broken,
      ].join("\n  "),
    );
  }
}

console.log("> Empty the shell's dist/");
rmSync(shellDist, { recursive: true, force: true });

console.log("> Compile src/ and the vendored hook with rslib");
run("rslib", ["build"]);

console.log("> Check every relative import in dist/ resolves");
assertRelativeImportsResolve();

console.log("> Generate the CSS entry from @monorepo/tailwind-config");
await buildGlobalsCss();
