/// <reference types="next" />
/// <reference types="next/image-types/global" />

// Ambient types for the non-TypeScript things this app imports: `*.css` as a
// side effect, and `*.png` as a `next/image` source.
//
// `next-env.d.ts` carries the same two references, but that file is generated by
// `next dev` / `next build` / `next typegen` and is gitignored — so a clean
// clone would otherwise fail `tsc` before it ever ran one of them. A `///`
// reference is idempotent: naming the same file twice adds nothing.
