import {
  BookOpenIcon,
  CalendarIcon,
  FilmIcon,
  GithubIcon,
  HomeIcon,
  LinkedinIcon,
  MailIcon,
  MapPinIcon,
  MedalIcon,
  MusicIcon,
  PhoneIcon,
  PlaneIcon,
} from "lucide-react";

export const DATA = {
  header: {
    title: "Hi, I'm Tuan",
    subtitle:
      "With a passion for programming, I constantly seek opportunities to learn, experiment, and apply new technology trends to products",
    avatarUrl: "/avatar.jpg",
  },
  about: {
    title: "About",
    data: [
      "Software Engineer with over 2 years of experience. Experienced in both Frontend and Backend development, capable of delivering full-stack solutions. A fast learner who adapts quickly to new technologies and works effectively under pressure.",
    ],
  },
  work: {
    title: "Work Experience",
    data: [
      {
        logoUrl: "/arobid.png",
        altText: "arobid",
        company: "AROBID",
        title: "Software Engineer",
        start: "May 2025",
        end: "Present",
        techStack: [
          "Monorepo",
          "React.js",
          "Next.js",
          "PayloadCMS",
          "Zustand",
          "TanStack Query",
          "Tailwind CSS",
          "MongoDB",
          "Radix UI",
          "Shadcn UI",
          "...",
        ],
        description: [
          "Developed and maintained the B2B Ecommerce system and TradeXpo platform, ensuring stable operation.",
          "Implemented a Monorepo structure to optimize workflows and share code efficiently between Frontend and Backend.",
          "Optimized frontend performance and SEO using advanced rendering techniques (ISR, SSR, CSR) with Next.js.",
          "Built full-stack features including CMS and landing pages using PayloadCMS.",
          "Integrated Shapespark SDK to build immersive 3D virtual environments for product showcasing.",
          "Implemented Lexorank algorithm to optimize drag-and-drop sorting performance for large datasets (Articles, FAQs).",
          "Collaborated with the Design team to build and maintain a consistent Design System.",
          "Utilized AI tools in the development workflow to speed up coding and problem-solving.",
        ],
      },
      {
        logoUrl: "/dcorp.png",
        altText: "dcorp",
        company: "DCORP R-KEEPER",
        title: "Frontend Developer",
        start: "Sep 2024",
        end: "May 2025",
        techStack: [
          "React.js",
          "Next.js",
          "Zustand",
          "TanStack Query",
          "Tailwind CSS",
          "Radix UI",
          "Shadcn UI",
          "Ant Design",
          "Storybook",
          "...",
        ],
        description: [
          "Developed and maintained core features for the CRM system to support customer management.",
          "Improved the internal Design System by standardizing reusable UI components.",
          "Built analytical dashboards using Recharts to visualize F\&B data (sales, inventory, customers).",
          "Optimized Shopping Cart logic and ordering workflows for the digital e-Menu application.",
          "Participated in the Highlands Coffee project (via VTI), developing Warehouse Management and Order Processing modules.",
        ],
      },
      {
        logoUrl: "/wisdom.jpg",
        altText: "wisdomrobotics",
        company: "WISDOMROBOTICS",
        title: "Software Engineer Intern",
        start: "Mar 2024",
        end: "Jun 2024",
        techStack: [
          "Express.js",
          "Next.js",
          "PostgreSQL",
          "Tailwind CSS",
          "Redux.js",
          "...",
        ],
        description: [
          "Learned the full Software Development Life Cycle (SDLC) through hands-on practice in a real-world project.",
          "Designed UI/UX flows for the vehicle maintenance system using Figma.",
          "Built the Backend codebase from scratch, setting up project structure and database schemas.",
          "Applied Next.js to build responsive and interactive user interfaces.",
        ],
      },
    ],
  },
  education: {
    title: "Education",
    data: [
      {
        logoUrl: "/stu.png",
        altText: "Saigon Technology University",
        href: "https://stu.edu.vn",
        school: "Saigon Technology University",
        degree: "Engineer Degree – Information Technology Engineering",
        start: "2020",
        end: "2024",
      },
    ],
  },
  skills: {
    title: "Skills",
    data: [
      "JavaScript",
      "TypeScript",
      "Java",
      "React.js",
      "Next.js",
      "Spring Boot",
      "Express.js",
      "Tailwind CSS",
      "PostgreSQL",
      "MongoDB",
      "Node.js",
      "Git",
      "Responsive",
    ],
  },
  navbar: [
    {
      href: "/#",
      label: "Home",
      icon: HomeIcon,
    },
    {
      href: "https://www.linkedin.com/in/tuan-huynh-916b792b7",
      label: "LinkedIn",
      icon: LinkedinIcon,
    },
    {
      href: "https://github.com/qtuan02",
      label: "GitHub",
      icon: GithubIcon,
    },
  ],
  contact: {
    title: "Contact",
    data: [
      {
        icon: CalendarIcon,
        href: "#",
        label: "20/07/2002",
      },
      {
        icon: PhoneIcon,
        href: "tel:+84393653862",
        label: "(+84) 393 653 862",
      },
      {
        icon: MapPinIcon,
        href: "#",
        label: "District 7, Ho Chi Minh city, Vietnam",
      },
      {
        icon: GithubIcon,
        href: "https://github.com/qtuan02",
        label: "github.com/qtuan02",
      },
      {
        icon: MailIcon,
        href: "mailto:huynhquoctuan200702@gmail.com",
        label: "huynhquoctuan200702@gmail.com",
      },
    ],
  },
  projects: {
    title: "Public Projects",
    data: [
      {
        title: "Assistant AI & MCP",
        description: "",
        techStack: [
          "Next.js",
          "TypeScript",
          "Shadcn UI",
          "Assistant UI",
          "Tailwind CSS",
          "Gemini",
          "Monorepo",
        ],
        image: "/projects/assistant-ai.jpg",
        github:
          "https://github.com/qtuan02/monorepo/tree/main/apps/assistant-ai",
        demo: "https://chat-assistant-ai-tuan.vercel.app",
        type: "Personal",
      },
      {
        title: "Document UI",
        description: "",
        techStack: [
          "Next.js",
          "TypeScript",
          "Shadcn UI",
          "Tailwind CSS",
          "Monorepo",
        ],
        image: "/projects/documents-ui.jpg",
        github: "https://github.com/qtuan02/monorepo/tree/main/apps/documents",
        demo: "https://documents-ui.vercel.app",
        type: "Personal",
      },
      {
        title: "TradeXpo Digital Exhibition Ecosystem on B2B Platform",
        description: "",
        techStack: [
          "Next.js",
          "TypeScript",
          "Shadcn UI",
          "Tailwind CSS",
          "SSR",
          "Monorepo",
        ],
        image: "/projects/tradexpo.jpg",
        github: "",
        demo: "https://arobid.com/tradexpo",
        type: "Company",
      },
      {
        title: "Careers Platform",
        description: "",
        techStack: [
          "Next.js",
          "TypeScript",
          "Shadcn UI",
          "Tailwind CSS",
          "SSR",
          "Monorepo",
        ],
        image: "/projects/careers.jpg",
        github: "",
        demo: "https://arobid.com/careers",
        type: "Company",
      },
      {
        title: "FAQs Platform",
        description: "",
        techStack: [
          "Next.js",
          "TypeScript",
          "Shadcn UI",
          "Tailwind CSS",
          "SSR",
          "ISR",
          "Monorepo",
        ],
        image: "/projects/faqs.jpg",
        github: "",
        demo: "https://arobid.com/help",
        type: "Company",
      },
      {
        title: "CMS & Management Platform",
        description: "",
        techStack: [
          "Next.js",
          "PayloadCMS",
          "TypeScript",
          "Tailwind CSS",
          "Shadcn UI",
          "MongoDB",
          "SSR",
          "ISR",
          "Monorepo",
        ],
        image: "/projects/cms-platform.jpg",
        github: "",
        demo: "https://arobid.com/tradexpo/vi/news",
        type: "Company",
      },
    ],
  },
  hobbies: {
    title: "Hobbies",
    data: [
      {
        icon: MedalIcon,
        label: "Sport",
      },
      {
        icon: BookOpenIcon,
        label: "Read book",
      },
      {
        icon: PlaneIcon,
        label: "Travel",
      },
      {
        icon: MusicIcon,
        label: "Listen music",
      },
      {
        icon: FilmIcon,
        label: "Watch movie",
      },
    ],
  },
};
