// Auto-generated component registry - do not edit
import { lazy   } from "react";
import type {LazyExoticComponent, ComponentType} from "react";

export type ComponentRegistry = Record<string, LazyExoticComponent<ComponentType<any>>>;

export const componentRegistry: ComponentRegistry = {
  "accordion": lazy(() => import("@monorepo/ui/components/accordion").then(m => ({ default: m.Accordion }))),
  "alert-dialog": lazy(() => import("@monorepo/ui/components/alert-dialog").then(m => ({ default: m.AlertDialog }))),
  "aspect-ratio": lazy(() => import("@monorepo/ui/components/aspect-ratio").then(m => ({ default: m.AspectRatio }))),
  "avatar": lazy(() => import("@monorepo/ui/components/avatar").then(m => ({ default: m.Avatar }))),
  "badge": lazy(() => import("@monorepo/ui/components/badge").then(m => ({ default: m.Badge }))),
  "breadcrumb": lazy(() => import("@monorepo/ui/components/breadcrumb").then(m => ({ default: m.Breadcrumb }))),
  "button": lazy(() => import("@monorepo/ui/components/button").then(m => ({ default: m.Button }))),
  "calendar": lazy(() => import("@monorepo/ui/components/calendar").then(m => ({ default: m.Calendar }))),
  "card": lazy(() => import("@monorepo/ui/components/card").then(m => ({ default: m.Card }))),
  "checkbox": lazy(() => import("@monorepo/ui/components/checkbox").then(m => ({ default: m.Checkbox }))),
  "collapsible": lazy(() => import("@monorepo/ui/components/collapsible").then(m => ({ default: m.Collapsible }))),
  "command": lazy(() => import("@monorepo/ui/components/command").then(m => ({ default: m.Command }))),
  "context-menu": lazy(() => import("@monorepo/ui/components/context-menu").then(m => ({ default: m.ContextMenu }))),
  "dialog": lazy(() => import("@monorepo/ui/components/dialog").then(m => ({ default: m.Dialog }))),
  "drawer": lazy(() => import("@monorepo/ui/components/drawer").then(m => ({ default: m.Drawer }))),
  "dropdown-menu": lazy(() => import("@monorepo/ui/components/dropdown-menu").then(m => ({ default: m.DropdownMenu }))),
  "form": lazy(() => import("@monorepo/ui/components/form").then(m => ({ default: m.FormItem }))),
  "hover-card": lazy(() => import("@monorepo/ui/components/hover-card").then(m => ({ default: m.HoverCard }))),
  "input-otp": lazy(() => import("@monorepo/ui/components/input-otp").then(m => ({ default: m.InputOTP }))),
  "input": lazy(() => import("@monorepo/ui/components/input").then(m => ({ default: m.Input }))),
  "label": lazy(() => import("@monorepo/ui/components/label").then(m => ({ default: m.Label }))),
  "menubar": lazy(() => import("@monorepo/ui/components/menubar").then(m => ({ default: m.Menubar }))),
  "navigation-menu": lazy(() => import("@monorepo/ui/components/navigation-menu").then(m => ({ default: m.NavigationMenu }))),
  "pagination": lazy(() => import("@monorepo/ui/components/pagination").then(m => ({ default: m.Pagination }))),
  "popover": lazy(() => import("@monorepo/ui/components/popover").then(m => ({ default: m.Popover }))),
  "progress": lazy(() => import("@monorepo/ui/components/progress").then(m => ({ default: m.Progress }))),
  "radio-group": lazy(() => import("@monorepo/ui/components/radio-group").then(m => ({ default: m.RadioGroup }))),
  "resizable": lazy(() => import("@monorepo/ui/components/resizable").then(m => ({ default: m.ResizablePanelGroup }))),
  "scroll-area": lazy(() => import("@monorepo/ui/components/scroll-area").then(m => ({ default: m.ScrollArea }))),
  "select": lazy(() => import("@monorepo/ui/components/select").then(m => ({ default: m.Select }))),
  "separator": lazy(() => import("@monorepo/ui/components/separator").then(m => ({ default: m.Separator }))),
  "sheet": lazy(() => import("@monorepo/ui/components/sheet").then(m => ({ default: m.Sheet }))),
  "skeleton": lazy(() => import("@monorepo/ui/components/skeleton").then(m => ({ default: m.Skeleton }))),
  "slider": lazy(() => import("@monorepo/ui/components/slider").then(m => ({ default: m.Slider }))),
  "sonner": lazy(() => import("@monorepo/ui/components/sonner").then(m => ({ default: m.Toaster }))),
  "switch": lazy(() => import("@monorepo/ui/components/switch").then(m => ({ default: m.Switch }))),
  "table": lazy(() => import("@monorepo/ui/components/table").then(m => ({ default: m.Table }))),
  "tabs": lazy(() => import("@monorepo/ui/components/tabs").then(m => ({ default: m.Tabs }))),
  "textarea": lazy(() => import("@monorepo/ui/components/textarea").then(m => ({ default: m.Textarea }))),
  "toggle-group": lazy(() => import("@monorepo/ui/components/toggle-group").then(m => ({ default: m.ToggleGroup }))),
  "toggle": lazy(() => import("@monorepo/ui/components/toggle").then(m => ({ default: m.Toggle }))),
  "tooltip": lazy(() => import("@monorepo/ui/components/tooltip").then(m => ({ default: m.Tooltip }))),
};
