# .air.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  # Build binary vào tmp/
  bin = "tmp/main.exe"
  cmd = "go build -o ./tmp/main.exe ./cmd/api"

  # Debounce thời gian rebuild (ms)
  delay = 1000

  # Watch/ignore
  exclude_dir = ["assets", "tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_unchanged = false
  follow_symlink = false

  # Run & stop behavior
  send_interrupt = true
  kill_delay = "500ms"
  stop_on_error = true

  # Log lỗi build (nếu có)
  log = "build-errors.log"

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
