// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  portfolio: "Portfolio";
  Exception: {
    back: "Come back";
    not_found: "Page Not Found";
    error: "Something went wrong";
  };
  Navbar: {
    home: "Home";
    about: "About";
    component: "Codes";
    vi_language: "Vietnamese";
    en_language: "English (US)";
  };
  Home: {
    title: "Hello, I'm Developer Frontend";
    subtitle: "You can call me Tuan";
    about: "About me";
    explore: "Explore";
  };
  About: {
    about_me: "About me";
    about_me_description: "With a passion for programming, I constantly seek opportunities to learn, experiment, and apply new technology trends to web products";
    download_cv: "Download CV";
    contact_info: "Contact Information";
    address: "District 7, Ho Chi Minh city, Vietnam";
    overview_description_1: "Hello! I'm Tuan, a Frontend Developer with over 1.5 years of experience in developing modern web applications. I'm passionate about building user interfaces that are visually appealing, easy to use, and performance-optimized.";
    overview_description_2: "I have experience working with React, Next.js, TypeScript, Tailwind CSS, and React Query, along with the ability to flexibly handle various rendering techniques such as CSR, SSR, SSG, and ISR. In addition, I am also proficient in implementing API Routes, Server Actions, and optimizing SEO for web applications.";
    overview_description_3: "In addition to my role as a Frontend Developer, I am also capable of handling certain Backend tasks, including building RESTful APIs, processing business logic, and connecting to databases.";
    overview_description_4: "I am always proactive in learning and staying up to date with the latest technology trends to continuously improve both product quality and my own skills. Outside of work, I enjoy reading tech books, playing sports, and traveling to explore new places. I believe that maintaining a healthy work-life balance is essential for sustaining creativity and productivity in my career.";
    experience: "Work Experience";
    education: "Education";
    hobbies: "Hobbies";
    major: "Information Technology Engineer";
    education_year: "Academic year";
    school: "Saigon Technology University";
    english_level: "English: Normal";
    sport: "Sports";
    read_book: "Read a book";
    travel: "Tourism";
    listen_music: "Listening to music";
    watch_movie: "Watch a movie";
    overview: "Overview";
    skills: "Skills";
    title: "About";
    description: "About";
    company_wisdomrobotics: "WISDOMROBOTICS COMPANY LIMITED";
    company_dcorp: "DCORP TECHNOLOGY JOINT STOCK COMPANY";
    company_arobid: "AROBID TECHNOLOGY JOINT STOCK COMPANY";
  };
  Docs: {
    title: "Codes";
    description: "Codes";
    "get-started": "Get started";
    introduction: "Introduction";
    components: "Components";
    animations: "Animations";
    "intro-content": {
      paragraph1: "This is a portfolio repo that belongs to a monorepo I built myself.";
      paragraph2: "It includes:";
      list: [
        "Components from shadcn and other components cloned/customized from various open-source projects.",
        "Tricks and best practices gathered during learning and development.",
        "A collection of useful custom hooks and utilities.",
        "Notes and practical examples that can be applied to other projects.",
      ];
      paragraph3: "The goal of this repo is to serve both as my personal portfolio and as a reusable set of components and tools for future projects.";
      paragraph4: "This project is built with SSG (Static Site Generation) and includes a sitemap to help Google Bot easily crawl the content and improve SEO.";
    };
    preview: "Preview";
    import: "Import";
    usage: "Usage";
    hooks: "Hooks";
    original: "Original";
    expands: "Expands";
  };
};
export default messages;
